# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jaeyoungyu/gamma/Gamma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jaeyoungyu/gamma/Gamma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaeyoungyu/gamma/Gamma/CMakeFiles /home/jaeyoungyu/gamma/Gamma/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaeyoungyu/gamma/Gamma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named Gamma

# Build rule for target.
Gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gamma
.PHONY : Gamma

# fast build rule for target.
Gamma/fast:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/build
.PHONY : Gamma/fast

Ast.o: Ast.cpp.o

.PHONY : Ast.o

# target to build an object file
Ast.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/Ast.cpp.o
.PHONY : Ast.cpp.o

Ast.i: Ast.cpp.i

.PHONY : Ast.i

# target to preprocess a source file
Ast.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/Ast.cpp.i
.PHONY : Ast.cpp.i

Ast.s: Ast.cpp.s

.PHONY : Ast.s

# target to generate assembly for a file
Ast.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/Ast.cpp.s
.PHONY : Ast.cpp.s

Gamma.o: Gamma.cpp.o

.PHONY : Gamma.o

# target to build an object file
Gamma.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/Gamma.cpp.o
.PHONY : Gamma.cpp.o

Gamma.i: Gamma.cpp.i

.PHONY : Gamma.i

# target to preprocess a source file
Gamma.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/Gamma.cpp.i
.PHONY : Gamma.cpp.i

Gamma.s: Gamma.cpp.s

.PHONY : Gamma.s

# target to generate assembly for a file
Gamma.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/Gamma.cpp.s
.PHONY : Gamma.cpp.s

LLparser.o: LLparser.cpp.o

.PHONY : LLparser.o

# target to build an object file
LLparser.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/LLparser.cpp.o
.PHONY : LLparser.cpp.o

LLparser.i: LLparser.cpp.i

.PHONY : LLparser.i

# target to preprocess a source file
LLparser.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/LLparser.cpp.i
.PHONY : LLparser.cpp.i

LLparser.s: LLparser.cpp.s

.PHONY : LLparser.s

# target to generate assembly for a file
LLparser.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/LLparser.cpp.s
.PHONY : LLparser.cpp.s

lexer.o: lexer.cpp.o

.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i

.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s

.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) -f CMakeFiles/Gamma.dir/build.make CMakeFiles/Gamma.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... intrinsics_gen"
	@echo "... Gamma"
	@echo "... Ast.o"
	@echo "... Ast.i"
	@echo "... Ast.s"
	@echo "... Gamma.o"
	@echo "... Gamma.i"
	@echo "... Gamma.s"
	@echo "... LLparser.o"
	@echo "... LLparser.i"
	@echo "... LLparser.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

